name: Publish Docker image
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set short Git-SHA
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-8)" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
          tags: |
            ghcr.io/gibstick/discord-azure-ad:${{ env.GITHUB_SHA_SHORT}}
            ghcr.io/gibstick/discord-azure-ad:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
